// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/api"
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/api/handler"
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/config"
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/db"
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/repository"
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/useCase"
)

// Injectors from wire.go:

func InitiateAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnToDB(cfg)
	if err != nil {
		return nil, err
	}
	adminRepository := repository.NewAdminRepository(gormDB)
	orderRepository := repository.NewOrderRepository(gormDB)
	adminService := usecase.NewAdminService(adminRepository, orderRepository)
	userRepository := repository.NewUserRepository(gormDB)
	paymentRepository := repository.NewPaymentRepository(gormDB)
	orderService := usecase.NewOrderUseCase(orderRepository, userRepository, paymentRepository)
	adminHandler := handler.NewAdminHandler(adminService, orderService)
	userService := usecase.NewUserUseCase(userRepository, orderRepository)
	userHandler := handler.NewUserHandler(userService)
	productRepository := repository.NewProductRepository(gormDB)
	productService := usecase.NewProductUseCase(productRepository)
	productHandler := handler.NewProductHandler(productService)
	paymentService := usecase.NewPaymentUseCase(paymentRepository, orderRepository)
	paymentHandler := handler.NewPaymentHandler(paymentService)
	orderHandler := handler.NewOrderHandler(orderService)
	couponRepository := repository.NewCouponRepository(gormDB)
	couponService := usecase.NewCouponUseCase(couponRepository)
	couponHandler := handler.NewCouponHandler(couponService)
	serverHTTP := http.NewServerHTTP(adminHandler, userHandler, productHandler, paymentHandler, orderHandler, couponHandler)
	return serverHTTP, nil
}
