// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/api"
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/api/handler"
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/config"
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/db"
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/repository"
	"github.com/Noush-012/Project-eCommerce-smart_gads/pkg/useCase"
)

// Injectors from wire.go:

func InitiateAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnToDB(cfg)
	if err != nil {
		return nil, err
	}
	adminRepository := repository.NewAdminRepository(gormDB)
	adminService := usecase.NewAdminService(adminRepository)
	adminHandler := handler.NewAdminHandler(adminService)
	userRepository := repository.NewUserRepository(gormDB)
	userService := usecase.NewUserUseCase(userRepository)
	userHandler := handler.NewUserHandler(userService)
	productRepository := repository.NewProductRepository(gormDB)
	productService := usecase.NewProductUseCase(productRepository)
	productHandler := handler.NewProductHandler(productService)
	serverHTTP := http.NewServerHTTP(adminHandler, userHandler, productHandler)
	return serverHTTP, nil
}
